---
apiVersion: v1
kind: Service
metadata:
  name: siglet
  namespace: vault-e2e-test
  labels:
    app: siglet
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: signaling
    port: 8081
    targetPort: signaling
    protocol: TCP
  selector:
    app: siglet